In [ ]:
import jieba
text = "小明毕业于北京大学计算机系"
word_generator = jieba.cut(text) # cut方法返回一个生成器
for word in word_generator:
    print(word)
    
word_list = jieba.lcut(text) # lcut方法返回一个列表
print(word_list)
# ['小明', '毕业', '于', '北京大学', '计算机系']

小明
毕业
于
北京大学
计算机系
['小明', '毕业', '于', '北京大学', '计算机系']


In [ ]:
import jieba
text = "小明毕业于北京大学计算机系"
word_generator = jieba.cut(text, cut_all=True) # cut方法返回一个生成器
for word in word_generator:
    print(word)
    
word_list = jieba.lcut(text, cut_all=True) # lcut方法返回一个列表
print(word_list)
# ['小', '明', '毕业', '于', '北京', '北京大学', '大学', '计算', '计算机', '计算机系', '算机', '系']

小
明
毕业
于
北京
北京大学
大学
计算
计算机
计算机系
算机
系
['小', '明', '毕业', '于', '北京', '北京大学', '大学', '计算', '计算机', '计算机系', '算机', '系']


In [ ]:
import jieba
text = "小明毕业于北京大学计算机系"
word_generator = jieba.cut_for_search(text) # cut方法返回一个生成器
for word in word_generator:
    print(word)
    
word_list = jieba.lcut_for_search(text) # lcut方法返回一个列表
print(word_list)
# ['小明', '毕业', '于', '北京', '大学', '北京大学', '计算', '算机', '计算机', '计算机系']

小明
毕业
于
北京
大学
北京大学
计算
算机
计算机
计算机系
['小明', '毕业', '于', '北京', '大学', '北京大学', '计算', '算机', '计算机', '计算机系']


In [ ]:
words_list = jieba.lcut("随着云计算技术的普及，越来越多企业开始采用云原生架构来部署服务，并借助大模型能力提升智能化水平，实现业务流程的自动化与智能决策。")
print(words_list)
# ['随着', '云', '计算技术', '的', '普及', '，', '越来越', '多', '企业', '开始', '采用', '云', '原生', '架构', '来', '部署', '服务', '，', '并', '借助', '大', '模型', '能力', '提升', '智能化', '水平', '，', '实现', '业务流程', '的', '自动化', '与', '智能', '决策', '。']
# 效果不佳，需要添加新词

['随着', '云', '计算技术', '的', '普及', '，', '越来越', '多', '企业', '开始', '采用', '云', '原生', '架构', '来', '部署', '服务', '，', '并', '借助', '大', '模型', '能力', '提升', '智能化', '水平', '，', '实现', '业务流程', '的', '自动化', '与', '智能', '决策', '。']


In [ ]:
jieba.load_userdict('./data/user_dict.txt')
words_list = jieba.lcut("随着云计算技术的普及，越来越多企业开始采用云原生架构来部署服务，并借助大模型能力提升智能化水平，实现业务流程的自动化与智能决策。")
print(words_list)
# ['随着', '云计算', '技术', '的', '普及', '，', '越来越', '多', '企业', '开始', '采用', '云原生', '架构', '来', '部署', '服务', '，', '并', '借助', '大模型', '能力', '提升', '智能化', '水平', '，', '实现', '业务流程', '的', '自动化', '与', '智能', '决策', '。']

['随着', '云计算', '技术', '的', '普及', '，', '越来越', '多', '企业', '开始', '采用', '云原生', '架构', '来', '部署', '服务', '，', '并', '借助', '大模型', '能力', '提升', '智能化', '水平', '，', '实现', '业务流程', '的', '自动化', '与', '智能', '决策', '。']


In [1]:
from gensim.models import KeyedVectors
model_path = './data/sgns.weibo.word.bz2'
model = KeyedVectors.load_word2vec_format(model_path, binary=False)

In [ ]:
print(model.vector_size) # 300
print(model['地铁']) # 词向量 一个300维的列表
similarity = model.similarity('地铁', '公交') # 计算两个词的相似度
print(similarity) # 0.65458214

300
[ 2.92064e-01 -5.18680e-02 -2.13720e-01  1.82131e-01  2.82900e-03
  4.14104e-01  1.56440e-01 -1.27940e-02 -3.28332e-01 -8.25000e-02
 -8.46890e-02 -2.14700e-02  1.18650e-01 -4.73659e-01 -1.97850e-02
  1.13939e-01  1.82734e-01 -6.46420e-02  5.60832e-01 -6.65230e-02
 -1.97960e-01  1.26039e-01 -3.28720e-01 -3.09730e-02 -3.46580e-01
 -1.53190e-01 -2.96226e-01 -5.75517e-01  1.10684e-01  8.19220e-02
 -1.04721e-01 -1.77477e-01 -1.21332e-01  1.49816e-01  2.86278e-01
 -8.11200e-03  6.72540e-02  6.92220e-02 -3.50973e-01 -5.49500e-02
 -7.80250e-02 -1.92952e-01 -1.70920e-01 -1.28289e-01  1.08204e-01
 -7.24913e-01 -1.11735e-01 -6.75000e-03  4.38086e-01 -8.75720e-02
 -1.41320e-01 -1.91726e-01  1.68363e-01 -7.85700e-02 -1.79772e-01
 -1.27950e-01  3.24675e-01  2.70616e-01  1.96330e-02 -3.09431e-01
 -4.02670e-02  5.80160e-02 -1.06603e-01  2.48022e-01  2.59204e-01
  2.16016e-01  3.96293e-01  2.48630e-02 -7.63330e-02  6.10183e-01
  2.73094e-01 -1.37777e-01  7.65180e-02 -1.35788e-01 -1.42440e-01
  1.22

In [ ]:
similar_words = model.most_similar(positive=["上班"], topn=5)
print(similar_words) # [('赶点', 0.6254161596298218), ('下班', 0.6208967566490173), ('车限行', 0.5995197296142578), ('车限号', 0.5659466981887817), ('赶得', 0.5646229982376099)]
result = model.most_similar(positive=["爸爸", "女性"], negative=["男性"], topn=3)
print(result) # [('妈妈', 0.45269083976745605), ('星爸', 0.439832478761673), ('爸妈', 0.43170687556266785)]

[('赶点', 0.6254161596298218), ('下班', 0.6208967566490173), ('车限行', 0.5995197296142578), ('车限号', 0.5659466981887817), ('赶得', 0.5646229982376099)]
[('妈妈', 0.45269083976745605), ('星爸', 0.439832478761673), ('爸妈', 0.43170687556266785)]


In [13]:
sentences = [['我', '每天','乘坐', '地铁', '上班'], ['我','每天', '乘坐', '公交', '上班']]
from gensim.models import Word2Vec
model = Word2Vec(sentences,        # 已分词的句子序列
                 vector_size=100,  # 词向量维度 
                 window=5,         # 上下文窗口大小 
                 min_count=2,      # 最小词频，低于该频率的词会被忽略
                 sg=1,             # 训练算法，1表示使用skip-gram，0表示使用CBOW 
                 workers=4         # 训练线程数
                 )

In [18]:
import jieba
from gensim.models import Word2Vec, KeyedVectors
import pandas as pd
df = pd.read_csv('./data/online_shopping_10_cats.csv', encoding='utf-8', usecols=['review']).dropna()
sentences = [[token for token in jieba.lcut(review) if token.strip() != ''] for review in df['review']]
model = Word2Vec(sentences, vector_size=100, window=5, min_count=2, sg=1, workers=4)

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'


In [ ]:
model.wv.save_word2vec_format('.data/my_vectors.kv')
my_model = KeyedVectors.load_word2vec_format('./data/my_vectors.kv')
print(my_model)

KeyedVectors<vector_size=100, 34576 keys>


In [ ]:
import torch
import torch.nn as nn
from gensim.models import KeyedVectors
# 1. 加载预训练词向量
word_vectors = KeyedVectors.load_word2vec_format('./data/my_vectors.kv')
# 2. 构建词表和词向量矩阵
word2index = word_vectors.key_to_index   # 词到索引的映射
embedding_dim = word_vectors.vector_size # 词向量维度
num_embeddings = len(word2index)         # 词表大小
embedding_matrix = torch.zeros((num_embeddings, embedding_dim)) # 初始化词向量矩阵
for word, idx in word2index.items():
    embedding_matrix[idx] = torch.tensor(word_vectors[word]) # 将预训练词向量填入矩阵
# 3. 构建PyTorch的Embedding层
embedding_layer = nn.Embedding.from_pretrained(
    embedding_matrix,  # 预训练词向量矩阵
    freeze=False        # 是否冻结词向量，True表示不更新词向量
)
# 4. 示例：将词索引转换为向量
input_words = ["我", "喜欢", "乘坐", "地铁"] # 分词后的句子
input_indices = [word2index[word] for word in input_words] # 将词转换为索引
input_tensor = torch.tensor(input_indices) # 转换为PyTorch张量
# 5. 查询嵌入
output = embedding_layer(input_tensor) # 获取词向量
print(output) # 输出词向量张量
print(output.shape) # 输出词向量的形状 torch.Size([4, 100])

tensor([[ 2.8621e-01, -8.4638e-02, -4.5371e-02,  6.5131e-02,  3.5452e-01,
         -2.5764e-01,  2.5537e-01,  2.2237e-01,  8.6644e-02, -2.7392e-02,
          2.2844e-01, -5.2078e-02,  3.0270e-01, -3.8430e-01, -2.6607e-01,
         -3.2037e-01,  4.4181e-01,  1.4127e-01, -3.3279e-01, -6.4381e-01,
          2.2388e-01, -1.9528e-01,  3.3641e-01, -1.7699e-01, -6.0854e-02,
          1.4282e-01, -1.2928e-01,  8.0006e-02, -2.9767e-02, -3.8403e-01,
          3.0495e-01, -2.1125e-01, -2.2084e-02, -4.0806e-02, -8.5079e-02,
          2.3305e-02,  3.4986e-01, -1.6115e-01, -1.0839e-01, -4.8296e-01,
         -3.3458e-02,  2.2847e-01, -2.8581e-01,  1.9475e-01,  1.0301e-01,
          1.7794e-01, -2.8221e-01, -1.8128e-01, -7.5307e-02,  3.1230e-01,
         -2.6670e-01, -8.5903e-02,  3.2314e-01, -4.9277e-02, -5.2312e-01,
          3.7045e-01, -2.3100e-02,  9.1796e-02, -2.6697e-01,  4.2295e-01,
          3.5264e-01, -8.5809e-02, -1.7427e-01, -2.3050e-01, -2.2231e-01,
          5.9921e-01,  1.4107e-01,  6.

In [31]:
# 处理OOV问题
unk_token = '<UNK>'
index2word = [unk_token] + word_vectors.index_to_key
word2index = {word: idx for idx, word in enumerate(index2word)}
embedding_dim = word_vectors.vector_size # 词向量维度
num_embeddings = len(word2index)         # 词表大小
embedding_matrix = torch.zeros((num_embeddings, embedding_dim)) # 初始化词向量矩阵
for word, idx in word2index.items():
    if word in word_vectors:
        embedding_matrix[idx] = torch.tensor(word_vectors[word]) # 将预训练词向量填入矩阵
    else:
        embedding_matrix[idx] = torch.randn(embedding_dim) * 0.01 # 对于OOV词，使用随机初始化的向量
# 3. 构建PyTorch的Embedding层
embedding_layer = nn.Embedding.from_pretrained(
    embedding_matrix,  # 预训练词向量矩阵
    freeze=False        # 是否冻结词向量，True表示不更新词向量
)
# 4. 示例：将词索引转换为向量
input_words = ["我", "喜欢", "乘坐", "宇宙飞船"] # 分词后的句子
input_indices = [word2index.get(word, 0) for word in input_words] # 将词转换为索引
input_tensor = torch.tensor(input_indices) # 转换为PyTorch张量
# 5. 查询嵌入
output = embedding_layer(input_tensor) # 获取词向量
print(output) # 输出词向量张量
print(output.shape) # 输出词向量的形状 torch.Size([4, 100])

tensor([[ 2.8621e-01, -8.4638e-02, -4.5371e-02,  6.5131e-02,  3.5452e-01,
         -2.5764e-01,  2.5537e-01,  2.2237e-01,  8.6644e-02, -2.7392e-02,
          2.2844e-01, -5.2078e-02,  3.0270e-01, -3.8430e-01, -2.6607e-01,
         -3.2037e-01,  4.4181e-01,  1.4127e-01, -3.3279e-01, -6.4381e-01,
          2.2388e-01, -1.9528e-01,  3.3641e-01, -1.7699e-01, -6.0854e-02,
          1.4282e-01, -1.2928e-01,  8.0006e-02, -2.9767e-02, -3.8403e-01,
          3.0495e-01, -2.1125e-01, -2.2084e-02, -4.0806e-02, -8.5079e-02,
          2.3305e-02,  3.4986e-01, -1.6115e-01, -1.0839e-01, -4.8296e-01,
         -3.3458e-02,  2.2847e-01, -2.8581e-01,  1.9475e-01,  1.0301e-01,
          1.7794e-01, -2.8221e-01, -1.8128e-01, -7.5307e-02,  3.1230e-01,
         -2.6670e-01, -8.5903e-02,  3.2314e-01, -4.9277e-02, -5.2312e-01,
          3.7045e-01, -2.3100e-02,  9.1796e-02, -2.6697e-01,  4.2295e-01,
          3.5264e-01, -8.5809e-02, -1.7427e-01, -2.3050e-01, -2.2231e-01,
          5.9921e-01,  1.4107e-01,  6.

In [1]:
import numpy as np

In [33]:
np.full_like(embedding_matrix, 0.01) # 创建一个与embedding_matrix形状相同的矩阵，所有元素初始化为0.01

array([[0.01, 0.01, 0.01, ..., 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, ..., 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, ..., 0.01, 0.01, 0.01],
       ...,
       [0.01, 0.01, 0.01, ..., 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, ..., 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, ..., 0.01, 0.01, 0.01]],
      shape=(34577, 100), dtype=float32)